codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: false

    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: true

  ignore:
    - "node_modules/"
    - "coverage/"
    - ".next/"
    - "dist/"
    - "**/*.test.*"
    - "**/*.spec.*"
    - "**/__tests__/**"
    - "cypress/"
    - "**/*.config.*"
    - "**/*.setup.*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true

flags:
  unittests:
    paths:
      - "src/"
    carryforward: true

  integration:
    paths:
      - "src/__tests__/integration/"
    carryforward: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Custom fix for Jest coverage paths
fixes:
  - "apps/tradeia/::"